[package]
name = "duct"
version = "0.11.0"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
documentation = "https://docs.rs/duct"
license = "MIT"

[dependencies]
os_pipe = "0.7.0"
shared_child = "0.3.2"
lazycell = "0.6.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.32"

[dev-dependencies]
tempdir = "0.3.5"
