[package]
name = "duct"
version = "0.5.1"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
license = "MIT"

[dependencies]
os_pipe = "^0.4.0"

[dev-dependencies]
tempdir = "^0.3.4"
