[package]
name = "duct"
version = "0.12.0"
authors = ["oconnor663@gmail.com"]
description = "a library for creating shell pipelines"
repository = "https://github.com/oconnor663/duct.rs"
documentation = "https://docs.rs/duct"
license = "MIT"
edition = "2018"

[dependencies]
os_pipe = "0.8.0"
shared_child = "0.3.3"
lazycell = "1.2.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2.43"

[dev-dependencies]
tempdir = "0.3.7"
